### ISSUE TITLE
Upgrade playbook fails to detect a binary patch version

### ISSUE THREAD

**Issue by guilhemmarchand** [thesplunker/Splunkenizer#14]
**Issue:** Upgrade procedure described in: https://github.com/splunkenizer/Splunkenizer/blob/master/docs/Upgrade_distributed_environment.md 

Will not detect the updated binary if the version is a patched version rather than a usual minor version increment, at the time of the writing the main version for Splunk core is:

- Splunk 8.0.4

Therefore it was patched for a last minute affecting bug with:

- Splunk 8.0.4.1

The upgrade playbook will terminate with:

`"msg": "Installed version '8.0.4' is equal to upgrade version '8.0.4' -> nothing to upgrade, ending"`

While the Software directory effectively contains both:

`rw-r--r-- 1 root root 511682204 Jun 26 11:28 /opt/xxxx/Software/splunk-8.0.4-767223ac207f-Linux-x86_64.tgz
-rwxr-x--- 1 root root 511705267 Jun 29 12:48 /opt/xxxx/Software/splunk-8.0.4.1-ab7a85abaa98-Linux-x86_64.tgz
`

Thank you!

**Comment by splunkenizer** [comment]
Hi

Detection of patched versions has been implemented since more than a year ago. There are several option, because this is not working in your environment:
- You are not running a current version of Splunkenizer
- You did not specify the new version in the playbook/inventory files
- You did not set the version to latest in the playbook/inventory files

I performed a quick test to verify again and it worked:
`"msg": "Upgrade splunk from version '8.0.4' to version '8.0.4.1'"`
