### ISSUE TITLE
support for provisioning existing VMs in ESXi

### ISSUE THREAD

**Issue by kundeng** [thesplunker/Splunkenizer#7]
Hi, great project!  Thank you!  It worked well on my personal laptop. 

You mentioned that you plan to support separating deployment and configuration.  Does it mean that it will in the future support existing VMs , say,  in ESXi?   I wanted to use this project to configure a test environment in our vsphere environment.

**Comment by splunkenizer** [comment]
Hi

Yes, that's the plan, but you can already do that using these steps:

- Configure the splunk_config.yml with the correct hosts, you have in you ESX infra
- Run 'vagrant status' an delet it create the ansible inventory for your configuration.
- Provision an ssh key to all hosts, which can be used by ansible.
- In order to let Splunkenizer use your key, create a directory for every hostname in 'inventory/host_vars/<hostname>'.
- create a file 'ansible_ssh_info.yml' in all the hostname directories with a config like this:

```
---
ansible_host: 172.16.1.100
ansible_port: 22
ansible_user: vagrant
ansible_ssh_private_key_file: "/<path_to_your_ssh_priv_key>/private_key"
```

Then you are able to run the ansible playbooks like described in the docs
